var res = {
    HelloWorld_png : "res/HelloWorld.png",
    boton_jugar_png : "res/boton_jugar.png",
    menu_titulo_png : "res/menu_titulo.png",
    tiles16_png: "res/tiles16.png",
    grass_png: "res/LPC Base Assets/tiles/grass.png",
    water_png: "res/LPC Base Assets/tiles/water.png",
    waterfall_png: "res/LPC Base Assets/tiles/waterfall.png",
    bridges_png: "res/LPC Base Assets/tiles/bridges.png",
    dirt_png: "res/LPC Base Assets/tiles/dirt.png",
    castlefloors_png: "res/LPC Base Assets/tiles/castlefloors.png",
    barrel_png: "res/LPC Base Assets/tiles/barrel.png",
    mapa1_tmx: "res/mapa1.tmx",
    mapa2_tmx: "res/mapa1_1.tmx",
    caballero_png: "res/caballero.png",
    caballero_plist: "res/caballero.plist",
    sara_png: "res/sprites.png",
    sara_plist: "res/sprites.plist",
    sara_portrait_png : "res/HUD/sara_portrait.png",
    menu_titulo_2_png : "res/main_screen.jpg",
    numberone_music : "res/music/number_one.mp3",
    effectfight_sound : "res/music/fightEffect.mp3",
    victory_sound : "res/music/victory_fanfare.mp3",
    hud_png : "res/HUD/hud.png",
    hud_plist : "res/HUD/hud.plist",
    hud_block_png : "res/HUD/hud.png",
    fondo_batalla_png : "res/HUD/background_00.jpg",
    mana_font_tff : {type:"font", name:"Manaspace", srcs:["res/fonts/manaspc.ttf"]},
    fondo_batalla_hud_png : "res/HUD/player_back_tab.png",
    health_bar_1_png : "res/HUD/bar.png",
    health_bar_1_overlay_png : "res/HUD/over_bar.png",
    heart_bar_png : "res/HUD/heart/heart_bar.png",
    heart_bar_plist : "res/HUD/heart/heart_bar.plist",
    robbie_png : "res/robbie/robbie.png",
    robbie_plist : "res/robbie/robbie.plist",
    sara_batalla_png : "res/LPC_Sara/sara_batalla.png",
    sara_batalla_plist : "res/LPC_Sara/sara_batalla.plist",
    bar_turns_png : "res/HUD/hud_bar_turns.png",
    banana_atack_png : "res/robbie/banana.png",
    meteor_attack_png : "res/robbie/meteor.png",
    fire_png : "res/LPC_Sara/attacks/fire.png",
    fire_plist : "res/LPC_Sara/attacks/fire.plist",
    ultima_png : "res/LPC_Sara/attacks/ultima.png",
    ultima_plist : "res/LPC_Sara/attacks/ultima.plist",
    fire_texture : "res/LPC_Sara/attacks/fire_texture.jpg",
    green_smoke_png : "res/LPC_Sara/attacks/green_smoke.png",
    green_smoke_plist : "res/LPC_Sara/attacks/green_smoke.plist",
    daggers_png : "res/LPC_Sara/attacks/daggers.png",
    daggers_plist : "res/LPC_Sara/attacks/daggers.plist",
    sara_death_png : "res/LPC_Sara/sara_death.png",
    sara_death_plist : "res/LPC_Sara/sara_death.plist",
    fight_music_1 : "res/music/fight_1.mp3",
    fight_music_2 : "res/music/fight_2.mp3",
    tragedy_music : "res/music/tragedy.mp3",
    potion_sound : "res/music/effects/potion.wav",
    dagger_1_sound : "res/music/effects/dagger_1.wav",
    dagger_2_sound : "res/music/effects/dagger_2.wav",
    magic_sound : "res/music/effects/magic.wav",
    malboro_green_png : "res/enemies/malboro_green.png",
    malboro_green_plist : "res/enemies/malboro_green.plist",
    fuerza_png : "res/LPC_Sara/level_up/strength.png",
    inteligencia_png : "res/LPC_Sara/level_up/intelligence.png",
    velocidad_png : "res/LPC_Sara/level_up/speed.png",
    run_away_png : "res/HUD/run.png",
};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}